import React from 'react'
import Footer from '../components/footer/Footer'
import AllEmployeeHeader from '../components/header/AllEmployeeHeader'
import AllEmployeeTableFilter from '../components/filter/AllEmployeeTableFilter'
import AllEmployeeTable from '../components/tables/AllEmployeeTable'
import Head from 'next/head'

const AllEmployeeMainContent = () => {
    return (
        <>
        <Head>
        <title>Digiboard - All Employee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="assets/favicon.png" />
        </Head>
        <div className="main-content">
            <div className="row">
                <div className="col-12">
                    <div className="panel">
                        <AllEmployeeHeader />
                        <div className="panel-body">
                            <AllEmployeeTableFilter />
                            <AllEmployeeTable />
                        </div>
                    </div>
                </div>
            </div>

            <Footer />
        </div>
        </>
        

    )
}

export default AllEmployeeMainContent