import React from 'react'
import Footer from '../components/footer/Footer'
import AllProductHeader from '../components/header/AllProductHeader'
import AllProductTableFilter from '../components/filter/AllProductTableFilter'
import AllProductTable from '../components/tables/AllProductTable'
import HeaderBtn from '../components/header/HeaderBtn'
import Head from 'next/head'

const AllProductMainContent = () => {
  return (
    <>
    <Head>
      <title>Digiboard - All Product</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="assets/favicon.png" />
    </Head>
    <div className="main-content">
        <div className="row g-4">
            <div className="col-12">
                <div className="panel">
                    <AllProductHeader/>
                    <div className="panel-body">
                        <HeaderBtn/>
                        <AllProductTableFilter/>
                        <AllProductTable/>
                    </div>
                </div>
            </div>
        </div>

        <Footer/>
    </div>
    </>
  )
}

export default AllProductMainContent
