import React from 'react'
import Footer from '../components/footer/Footer'
import FullCalender from '../components/calender/FullCalendarComponent'
import UpcomingEvents from '../components/calender/UpcomingEvents'
import ReservedEvents from '../components/calender/ReservedEvents'
import Head from 'next/head'
const CalendarMainContent = () => {
  return (
    <>
    <Head>
      <title>Digiboard - eCommerce Dashboard</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="assets/favicon.png" />
    </Head>
    <div className="main-content">
      <div className="row">
        <FullCalender />
        <div className="col-xxl-3 col-lg-4 calendar-sidebar">
          <ReservedEvents />
          <UpcomingEvents />
        </div>
      </div>

      <Footer />
    </div>
    </>
    

  )
}

export default CalendarMainContent