import React from 'react'
import Footer from '../components/footer/Footer'
import AddNewCategory from '../components/category/AddNewCategory'
import AllCategory from '../components/category/AllCategory'
import Head from 'next/head'
import DashboardBreadcrumb2 from '@/components/breadcrumb/DashboardBreadcrumb2'

const CategoryMainContent = () => {
  return (
    <>
    <Head>
      <title>Digiboard - Category</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="assets/favicon.png" />
    </Head>
    <div className="main-content">
      <DashboardBreadcrumb2 title={'Categories'}/>
      <div className="row g-4">
          <AddNewCategory/>
          <AllCategory/>
      </div>

      <Footer/>
    </div>
    </>
    
    
  )
}

export default CategoryMainContent