import ComingSoonContent2 from '@/components/coming-soon/ComingSoonContent2'
import Head from 'next/head'
import React from 'react'

const comingSoon = () => {
  return (
    <>
    <Head>
      <title>Digiboard - Coming Soon Page 2</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="assets/favicon.png" />
    </Head>
    <ComingSoonContent2/>
    </>
  )
}

export default comingSoon