import React from 'react'
import Footer from '../components/footer/Footer'
import ContactForm1 from '../components/forms/ContactForm1'
import ContactForm2 from '../components/forms/ContactForm2'
import ContactForm3 from '../components/forms/ContactForm3'
import ContactForm4 from '../components/forms/ContactForm4'
import Head from 'next/head'
import DashboardBreadcrumb2 from '@/components/breadcrumb/DashboardBreadcrumb2'

const ContactsMainContent = () => {
  return (
    <>
    <Head>
      <title>Digiboard - Contact</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="assets/favicon.png" />
    </Head>
      <div className="main-content">
        <DashboardBreadcrumb2 title={'Contact Forms'}/>
        <div className="row g-4">
            <ContactForm1/>
            <ContactForm2/>
            <ContactForm3/>
            <ContactForm4/>
        </div>

        <Footer/>
    </div>
    </>
    
    
  )
}

export default ContactsMainContent