import Footer from '../components/footer/Footer'
import CustomerHeader from '../components/header/CustomerHeader'
import CustomerTableFilter from '../components/filter/CustomerTableFilter';
import CustomerTable from '../components/tables/CustomerTable';
import Head from 'next/head';
const CustomerMainContent = () => {
    return (
        <>
        <Head>
        <title>Digiboard - Customer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="assets/favicon.png" />
        </Head>
        <div className="main-content">
            <div className="row">
                <div className="col-12">
                    <div className="panel">
                        <CustomerHeader />
                        <div className="panel-body">
                            <CustomerTableFilter />
                            <CustomerTable />
                        </div>
                    </div>
                </div>
            </div>
            <Footer />
        </div>

        </>
        
    )
}

export default CustomerMainContent