import ErrorContent from '@/components/error/ErrorContent'
import Head from 'next/head'
import React from 'react'

const error404 = () => {
  return (
    <>
    <Head>
      <title>Digiboard - Error 404</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="assets/favicon.png" />
    </Head>
    <ErrorContent imgSrc={"assets/images/error-404.png"} alt={'404'} subtitle={'Page Not Found'}/>
    </>
  )
}

export default error404