import { useCallback, useEffect, useState } from "react";
import DashboardBreadcrumb from "@/components/breadcrumb/DashboardBreadcrumb";
import DashboardCards from "@/components/cards/DashboardCards";
import NewCustomer from "@/components/dashboard/NewCustomer";
import RecentOrder from "@/components/dashboard/RecentOrder";
import SalesAnalytics from "@/components/dashboard/SalesAnalytics";
import SocialVisitors from "@/components/dashboard/SocialVisitors";
import Footer from "@/components/footer/Footer";
import { fetchAdminDashboard } from "@/lib/avenueClient";
import Head from "next/head";

export default function Home() {
  const [days, setDays] = useState(7);
  const [dashboard, setDashboard] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const loadDashboard = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const data = await fetchAdminDashboard({ days });
      setDashboard(data);
    } catch (err) {
      setError(err.message || "Failed to load dashboard");
      setDashboard(null);
    } finally {
      setLoading(false);
    }
  }, [days]);

  useEffect(() => {
    loadDashboard();
  }, [loadDashboard]);

  return (
    <>
      <Head>
        <title>Digiboard - eCommerce Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="assets/favicon.png" />
      </Head>
      <div className="main-content">
        <DashboardBreadcrumb title="eCommerce Dashboard" />

        {error && (
          <div className="alert alert-danger d-flex justify-content-between align-items-center mb-3">
            <span>{error}</span>
            <button type="button" className="btn btn-sm btn-outline-danger" onClick={loadDashboard}>
              Retry
            </button>
          </div>
        )}

        <DashboardCards summary={dashboard?.summary} loading={loading} />
        <div className="row">
          <SalesAnalytics
            chart={dashboard?.chart}
            days={days}
            onDaysChange={setDays}
            loading={loading}
          />
          <SocialVisitors />
          <NewCustomer customers={dashboard?.newCustomers} loading={loading} />
          <RecentOrder orders={dashboard?.recentOrders} loading={loading} />
        </div>
        <Footer />
      </div>
    </>
  );
}
