import Footer from '../components/footer/Footer';
import LeadsHeader from '../components/header/LeadsHeader';
import LeadsTableFilter from '../components/filter/LeadsTableFilter';
import LeadsTable from '../components/tables/LeadsTable';
import Layout from '@/components/layout/Layout';
import Head from 'next/head';
const LeadsMainContent = () => {


    return (
        <>
        <Head>
        <title>Digiboard - Leads</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="assets/favicon.png" />
        </Head>
        <div className="main-content">
            <div className="row">
                <div className="col-12">
                    <div className="panel">
                        <LeadsHeader />
                        <div className="panel-body">
                            <LeadsTableFilter />
                            <LeadsTable />
                        </div>
                    </div>
                </div>
            </div>

            <Footer />
        </div>
        </>
    )
}

export default LeadsMainContent