import React from 'react'
import LoginContent2 from '../components/login/LoginContent2'
import Head from 'next/head'

const Login2 = () => {
  return (
    <>
    <Head>
      <title>Digiboard - Login Page 2</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="assets/favicon.png" />
    </Head>
    <LoginContent2/>
    </>
  )
}

export default Login2