import React from 'react'
import LoginContent from '../components/login/LoginContent'
import Head from 'next/head'

const Login = () => {
  return (
    <>
    <Head>
      <title>Digiboard - Login Page</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="assets/favicon.png" />
    </Head>
    <LoginContent/>
    </>
  )
}

export default Login