import LoginContent3 from '@/components/login/LoginContent3'
import Head from 'next/head'
import React from 'react'

const login3 = () => {
  return (
    <>
    <Head>
      <title>Digiboard - Login 03</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="assets/favicon.png" />
    </Head>
    <LoginContent3/>
    </>
  )
}

export default login3