import React from 'react'
import LoginStatusContent from '../components/login/LoginStatusContent'
import Head from 'next/head'

const LoginStatus = () => {
  return (
    <>
    <Head>
      <title>Digiboard - Login Status</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="assets/favicon.png" />
    </Head>
    <LoginStatusContent/>
    </>
  )
}

export default LoginStatus