import PricingTableContent2 from '@/components/pricing-table/PricingTableContent2'
import Head from 'next/head'
import React from 'react'

const pricingTable2 = () => {
  return (
    <>
    <Head>
      <title>Digiboard - Pricing Table 2</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="assets/favicon.png" />
    </Head>
    <PricingTableContent2/>
    </>
  )
}

export default pricingTable2