import React from 'react'
import RegistrationContent from '../components/registration/RegistrationContent'
import Head from 'next/head'

const Registration = () => {
  return (
    <>
    <Head>
      <title>Digiboard - Registration Page</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="assets/favicon.png" />
    </Head>
    <RegistrationContent/>
    </>
  )
}

export default Registration