import React from 'react'
import RegistrationContent2 from '../components/registration/RegistrationContent2'
import Head from 'next/head'

const Registration2 = () => {
  return (
    <>
    <Head>
      <title>Digiboard - Registration Page 2</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="assets/favicon.png" />
    </Head>
    <RegistrationContent2/>
    </>
  )
}

export default Registration2