import Head from 'next/head'
import Link from 'next/link'
import React from 'react'

const underConstruction = () => {
  return (
    <>
    <Head>
      <title>Digiboard - Under Construction</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="assets/favicon.png" />
    </Head>
    <div className="main-content p-0">
      <div className="panel under-construction-panel">
        <div className="panel-body h-100 d-flex flex-column align-items-center justify-content-center">
          <div className="part-img">
            <img src="assets/images/under-construction.png" alt="coming-soon" />
          </div>
          <div className="part-txt">
            <h2>Under Construction</h2>
            <p>To make things right we need some time to rebuild</p>
            <Link
              href="/"
              className="btn btn-primary py-2 px-5 rounded-pill"
            >
              Go To Home
            </Link>
          </div>
        </div>
      </div>
    </div>
    </>
  )
}

export default underConstruction